---
title: "Shiny app"
author: Chih-Ying Deng, Danni Lin, Bing Shao Chia
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reshape)
library(reshape2)
library(plotly)
library(shiny)
library(crosstalk)
library(forcats)
library(tidyr)
```


```{r}
question <- read.csv('data/question.csv') 
head(question)
```

```{r}
q_list<- read.csv('data/question_list.csv') 
q_list
```


```{r, echo=FALSE}
data <- read.csv('data/data_code.csv')
head(data)
```


```{r, echo=FALSE, warning=FALSE}
ui <- fluidPage(
  titlePanel("Mental Illness in Tech Compancy"),
  sidebarPanel(
    selectInput("Gender", 
                  label = "Gender:",
                  choices = c('All', as.character(unique(data$What.is.your.gender))),
                  multiple = FALSE),
    selectInput("Selfemployed", 
                  label = "Self-employed:",
                  choices = c('All', as.character(unique(data$Are.you.selfemployed))),
                  multiple = FALSE),
    selectInput("FamilyHx", 
                  label = "Family history of mental illness:",
                  choices = c('All', as.character(unique(data$Do.you.have.a.family.history.of.mental.illness))),
                  multiple = FALSE),
    sliderInput("Age", 
                  label = "Age:",
                  min = 1, max = 99, value = c(1, 99)),
    checkboxGroupInput("QA", 
                  label = "Question Answer:",
                  choices = c("Yes","No","Maybe"),
                  selected = c("Yes","No","Maybe"))
  ),
  
  mainPanel(
    plotlyOutput("map"),
    plotlyOutput("stat"),    
    plotlyOutput("plot"), 
    verbatimTextOutput("question"),
    verbatimTextOutput("click")
  )
);

server <- function(input, output,session) {
     pre <- function(data){
          lst <- data
          if (input$Gender!="All"){
               lst <- lst %>% 
                    filter(What.is.your.gender==input$Gender)  
          }
          if (input$Selfemployed!="All"){
               lst <- lst %>% 
                    filter(Are.you.selfemployed==input$Selfemployed)  
          }
          if (input$FamilyHx!="All"){
               lst <- lst %>% 
                    filter(Do.you.have.a.family.history.of.mental.illness==input$FamilyHx)  
          }
          lst <- lst %>% filter(What.is.your.age>=input$Age[1] & What.is.your.age<=input$Age[2])  
          return(lst)
     }
     
  output$map <- renderPlotly({
     lst <- pre(data)
     lst <- as.data.frame(table(lst$live_state_code))
     names(lst) <- c('country','count') 
     lst <- lst %>% filter(country!='')
     sd <- SharedData$new(lst)
     l <- list(color = toRGB("grey"), width = 0.5)
     g <- list(
       showframe = FALSE,
       showcoastlines = TRUE,
       projection = list(type = 'albers usa') # Mercator
     )
     
     p <- plot_geo(sd, locationmode = 'USA-states') %>%
       add_trace(
         z = ~count, color = ~count, colors = 'Blues',
         text = ~country, locations = ~country, marker = list(line = l)
       ) %>%
       colorbar(title = 'people') %>%
       layout(
         title = 'Live states of the participants',
         geo = g
       ) 
     p
  })
  
  output$stat <- renderPlotly({
    lst <- pre(data)
    gender <- as.data.frame(table(lst$What.is.your.gender)) 
    gender$cumsum <- cumsum(gender$Freq)-120
    selfem <- as.data.frame(table(lst$Are.you.selfemployed))
    selfem$cumsum <- cumsum(selfem$Freq)-120
    fhx <- as.data.frame(table(lst$Do.you.have.a.family.history.of.mental.illness))
    fhx$cumsum <- cumsum(fhx$Freq)-120
    p1_1 <- plot_ly(gender) %>% 
          add_bars(x=~Freq, y=~Var1, color=~Var1, colors = 'YlGnBu') %>%
          layout(yaxis = list(title="Gender"))
    p1_2 <- plot_ly(selfem) %>% 
          add_bars(x=~Freq, y=~Var1, color=~Var1, colors = 'Set2') %>%
          layout(yaxis = list(title="Self-Employed")) 
    p1_3 <- plot_ly(fhx) %>% 
          add_bars(x=~Freq, y=~Var1, color=~Var1, colors = 'Set3') %>%
          layout(yaxis = list(title="Family_Hx")) 
    s1 <- subplot(p1_1, p1_2, p1_3, nrows = 3, shareX = TRUE,
                  titleX = FALSE, titleY = TRUE) %>%
          layout(title = 'Demographics of the participants', barmode='group', showlegend = FALSE) 
    s1
  })   
  
  output$plot <- renderPlotly({
     lst <- pre(data)
     if (input$Selfemployed!="All"){
          lst <- lst %>% filter(Are.you.selfemployed==input$Selfemployed)  
     }
     sub <- question %>% filter(ResponseID %in% unique(lst$ResponseID)) %>%  
            filter(Q!='')
     sub$f <- 1
     sub <- sub %>% cast(Q~A, sum, value="f") %>% 
            melt(id = c("Q")) %>% filter(A %in% input$QA) 
     levels(sub$Q) <- paste("Q", 1:42, sep = "")
     plot_ly(sub) %>% 
          add_bars(x=~Q, y=~value, color=~A, colors = "YlOrRd") %>%
          layout(title ="Response to the 42 questions", barmode = 'stack',
                 xaxis = list(title="Question"),
                 yaxis = list(title="Response"))

  })  
  
  output$question <- renderPrint({
     print(q_list$Question)
  })
  output$click <- renderPrint({
    d <- event_data("plotly_relayout")
    if (!is.null(d)){
        invisible(updateSliderInput(session, "range", value = c(d[[1]], d[[2]])))
    }
  });
};

shinyApp(ui, server, options = list(height=600));
```



